// Generated for: react-router-streaming 1.0.0.0
// Generated by: Microsoft.JavaScript.NodeApi.Generator 0.9.0.0
/* eslint-disable */

import './System.Runtime';


export interface greeterService {
	greetAsync(name: string): Promise<string>;
}
